[package]
name = "siri"
version = "0.1.0"
authors = ["Sam Donow <drsam94@gmail.com>", "Jefferson Airplane Guanciale <il@yakay.li>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
